export const langs = [
   {
      "lang_name":"Auto",
      "lang_code":"auto"
   },
   {
      "lang_name":"Afrikaans",
      "lang_code":"af"
   },
   {
      "lang_name":"Albanian",
      "lang_code":"sq"
   },
   {
      "lang_name":"Amharic",
      "lang_code":"am"
   },
   {
      "lang_name":"Arabic",
      "lang_code":"ar"
   },
   {
      "lang_name":"Armenian",
      "lang_code":"hy"
   },
   {
      "lang_name":"Azerbaijani",
      "lang_code":"az"
   },
   {
      "lang_name":"Bengali",
      "lang_code":"bn"
   },
   {
      "lang_name":"Bosnian",
      "lang_code":"bs"
   },
   {
      "lang_name":"Bulgarian",
      "lang_code":"bg"
   },
   {
      "lang_name":"Catalan",
      "lang_code":"ca"
   },
   {
      "lang_name":"Chinese (Simplified)",
      "lang_code":"zh"
   },
   {
      "lang_name":"Chinese (Traditional)",
      "lang_code":"zh-TW"
   },
   {
      "lang_name":"Croatian",
      "lang_code":"hr"
   },
   {
      "lang_name":"Czech",
      "lang_code":"cs"
   },
   {
      "lang_name":"Danish",
      "lang_code":"da"
   },
   {
      "lang_name":"Dari",
      "lang_code":"fa-AF"
   },
   {
      "lang_name":"Dutch",
      "lang_code":"nl"
   },
   {
      "lang_name":"English",
      "lang_code":"en"
   },
   {
      "lang_name":"Estonian",
      "lang_code":"et"
   },
   {
      "lang_name":"Farsi (Persian)",
      "lang_code":"fa"
   },
   {
      "lang_name":"Filipino Tagalog",
      "lang_code":"tl"
   },
   {
      "lang_name":"Finnish",
      "lang_code":"fi"
   },
   {
      "lang_name":"French",
      "lang_code":"fr"
   },
   {
      "lang_name":"French (Canada)",
      "lang_code":"fr-CA"
   },
   {
      "lang_name":"Georgian",
      "lang_code":"ka"
   },
   {
      "lang_name":"German",
      "lang_code":"de"
   },
   {
      "lang_name":"Greek",
      "lang_code":"el"
   },
   {
      "lang_name":"Gujarati",
      "lang_code":"gu"
   },
   {
      "lang_name":"Haitian Creole",
      "lang_code":"ht"
   },
   {
      "lang_name":"Hausa",
      "lang_code":"ha"
   },
   {
      "lang_name":"Hebrew",
      "lang_code":"he"
   },
   {
      "lang_name":"Hindi",
      "lang_code":"hi"
   },
   {
      "lang_name":"Hungarian",
      "lang_code":"hu"
   },
   {
      "lang_name":"Icelandic",
      "lang_code":"is"
   },
   {
      "lang_name":"Indonesian",
      "lang_code":"id"
   },
   {
      "lang_name":"Italian",
      "lang_code":"it"
   },
   {
      "lang_name":"Japanese",
      "lang_code":"ja"
   },
   {
      "lang_name":"Kannada",
      "lang_code":"kn"
   },
   {
      "lang_name":"Kazakh",
      "lang_code":"kk"
   },
   {
      "lang_name":"Korean",
      "lang_code":"ko"
   },
   {
      "lang_name":"Latvian",
      "lang_code":"lv"
   },
   {
      "lang_name":"Lithuanian",
      "lang_code":"lt"
   },
   {
      "lang_name":"Macedonian",
      "lang_code":"mk"
   },
   {
      "lang_name":"Malay",
      "lang_code":"ms"
   },
   {
      "lang_name":"Malayalam",
      "lang_code":"ml"
   },
   {
      "lang_name":"Maltese",
      "lang_code":"mt"
   },
   {
      "lang_name":"Mongolian",
      "lang_code":"mn"
   },
   {
      "lang_name":"Norwegian",
      "lang_code":"no"
   },
   {
      "lang_name":"Persian",
      "lang_code":"fa"
   },
   {
      "lang_name":"Pashto",
      "lang_code":"ps"
   },
   {
      "lang_name":"Polish",
      "lang_code":"pl"
   },
   {
      "lang_name":"Portuguese",
      "lang_code":"pt"
   },
   {
      "lang_name":"Romanian",
      "lang_code":"ro"
   },
   {
      "lang_name":"Russian",
      "lang_code":"ru"
   },
   {
      "lang_name":"Serbian",
      "lang_code":"sr"
   },
   {
      "lang_name":"Sinhala",
      "lang_code":"si"
   },
   {
      "lang_name":"Slovak",
      "lang_code":"sk"
   },
   {
      "lang_name":"Slovenian",
      "lang_code":"sl"
   },
   {
      "lang_name":"Somali",
      "lang_code":"so"
   },
   {
      "lang_name":"Spanish",
      "lang_code":"es"
   },
   {
      "lang_name":"Spanish (Mexico)",
      "lang_code":"es-MX"
   },
   {
      "lang_name":"Swahili",
      "lang_code":"sw"
   },
   {
      "lang_name":"Swedish",
      "lang_code":"sv"
   },
   {
      "lang_name":"Tagalog",
      "lang_code":"tl"
   },
   {
      "lang_name":"Tamil",
      "lang_code":"ta"
   },
   {
      "lang_name":"Telugu",
      "lang_code":"te"
   },
   {
      "lang_name":"Thai",
      "lang_code":"th"
   },
   {
      "lang_name":"Turkish",
      "lang_code":"tr"
   },
   {
      "lang_name":"Ukrainian",
      "lang_code":"uk"
   },
   {
      "lang_name":"Urdu",
      "lang_code":"ur"
   },
   {
      "lang_name":"Uzbek",
      "lang_code":"uz"
   },
   {
      "lang_name":"Vietnamese",
      "lang_code":"vi"
   },
   {
      "lang_name":"Welsh",
      "lang_code":"cy"
   }
]